version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install "poetry>=1.2.0,<1.3.0"
      - poetry config virtualenvs.create false
      - poetry install

# Build documentation with Sphinx
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true
